"use client"

import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import "./globals.css"
import MainHeader from "./components/headers/MainHeader";
import MainFooter from "./footers/FooterMain";

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Gobi Today",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  useEffect(() => {
    console.log("AOS initializing...");
    AOS.init({
      duration: 2000,
      // once: true,
    });
    console.log("AOS initialized!");
  }, []);
  

  return (
    <html lang="en">
      <body className={inter.className}>
      <MainHeader data-aos="fade-up" />
        {children}
        <MainFooter data-aos="fade-up" />

        </body>
    </html>
  );
}
